export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";

export const FETCH_TOP_HOLDERS_SUCCESS = "FETCH_TOP_HOLDERS_SUCCESS";
export const FETCHING_TOP_HOLDERS = "FETCHING_TOP_HOLDERS";
export const FETCH_TOP_HOLDERS_FAILED = "FETCH_TOP_HOLDERS_FAILED";
